WebApplication11/Areas/Admin/Controllers/WriterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication11.Areas.Admin.Models;

namespace WebApplication11.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WriterController : Controller
    {
        
        
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WriterList()
        {
            var jsonWriters=JsonConvert.SerializeObject(writers);
           
            return Json(jsonWriters);
        }
        public IActionResult GetWriterByID(int id)
        {
            var findWriter = writers.FirstOrDefault(x => x.Id == id);
            var jsonWriters = JsonConvert.SerializeObject(findWriter);

            return Json(jsonWriters);
        }
        public static List<WriterClass> writers = new List<WriterClass>
        {
            new WriterClass
            {
                Id=1,
                Name ="Ayşe"
            },
       new WriterClass
            {
                Id=2,
                Name ="Aybike"
            },
        new WriterClass
{
    Id = 3,
                Name = "Ayla"
}
        };
    }
}

WebApplication11/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    [AllowAnonymous]
    public class WriterController : Controller
    {

        WriterManager writerManager = new WriterManager(new EfWriterRepository());
    

        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }
        [HttpGet]
        public IActionResult WriterEditProfile()
        {
            var values = writerManager.TGetById(1);
            return View(values);
        }
        [HttpPost]
        public IActionResult WriterEditProfile(Writer p)
        {
            WriterValidator wl = new WriterValidator();
            ValidationResult result = wl.Validate(p);
            if (result.IsValid)
            {
               writerManager.TUpdate(p);
                return RedirectToAction("Index","Dashboard");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult LogOut()
        {
            

            return RedirectToAction("Index", "Login");
        }

    }
}
 

WebApplication11/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>Burası yazar paneli</h1>
<br />
<h2>@ViewBag.v</h2>
<br />
<h3>Hoşgeldiniz @ViewBag.v2</h3>

WebApplication11/Views/Writer/LogOut.cshtml
@{
    ViewData["Title"] = "LogOut";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
		<div class="container">
				<h3 class="tittle">Oturum Aç</h3>
				<div class="row inner-sec">
					<div class="login p-5 bg-light mx-auto mw-100">
					<form  method="post">
							<div class="form-group">
							  <label for="exampleInputEmail1 mb-2">Mail adresiniz</label>
							  <input type="email" class="form-control" name="WriterMail" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
							
							</div>
							<div class="form-group">
							  <label for="exampleInputPassword1 mb-2">Şifre</label>
							  <input type="password"  name="WriterPassword" class="form-control" id="exampleInputPassword1" placeholder="" required="">
							</div>
							<div class="form-check mb-2">
							  <input type="checkbox" class="form-check-input" id="exampleCheck1">
							  <label class="form-check-label" for="exampleCheck1">Beni hatırla</label>
							</div>
							<button type="submit" class="btn btn-primary submit mb-4">Giriş Yap</button>
							<p><a href="/Register/Index/"> Henüz bir hesabın yok mu?</a></p>
						  </form>
		</div>
		</div>
	</div>
	</section>

WebApplication11/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>testt</h1>

WebApplication11/Views/Writer/WriterAdd.cshtml
@model WebApplication11.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                 
                    <div class="forms-sample">
                      <div class="form-group">
                        <label for="exampleInputName1">Yazar Adı-Soyadı</label>
                        @Html.TextBoxFor(x=>x.WriterName,new{@class="form-control"})
                    @*    <input type="text" class="form-control" id="exampleInputName1" name="WriterName" placeholder="Name">*@
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                     @Html.TextBoxFor(x=>x.WriterMail,new{@class="form-control"})
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.PasswordFor(x=>x.WriterPassword,new{@class="form-control"})
                      </div>
                 
                      <div class="form-group">
                        <label> Yazar Görsel</label>
                    <input type="file" name="WriterImage" />
                        </div>
                      </div>
                
                      <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                         @Html.TextAreaFor(x=>x.WriterAbout,10,3,new{@class="form-control"})
                      </div>
                      <button type="submit" class="btn btn-gradient-primary me-2">Kaydet</button>
                      <button class="btn btn-light">İptal</button>
                    </div>
                  </div>
                </div>
              
</form>

WebApplication11/Views/Writer/WriterEditProfile.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post))
{
                <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                      @Html.TextBoxFor(x=>x.WriterID,new{@class="form-control"})
                    <form class="forms-sample">
                      <div class="form-group">
                        <label for="exampleInputName1">Yazar Adı-Soyadı</label>
                        @Html.TextBoxFor(x=>x.WriterName,new{@class="form-control"})
                    @*    <input type="text" class="form-control" id="exampleInputName1" name="WriterName" placeholder="Name">*@
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                     @Html.TextBoxFor(x=>x.WriterMail,new{@class="form-control"})
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.PasswordFor(x=>x.WriterPassword,new{@class="form-control"})
                      </div>
                 
                      <div class="form-group">
                        <label> Yazar Görsel</label>
                        <input type="file" name="img[]" class="file-upload-default">
                        <div class="input-group col-xs-12">
                          <input type="text" class="form-control file-upload-info" disabled placeholder="Resim Seç">
                          <span class="input-group-append">
                            <button class="file-upload-browse btn btn-gradient-primary" type="button">Yükle</button>
                          </span>
                        </div>
                      </div>
                
                      <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                         @Html.TextAreaFor(x=>x.WriterAbout,10,3,new{@class="form-control"})
                      </div>
                      <button type="submit" class="btn btn-gradient-primary me-2">Güncelle</button>
                      <button class="btn btn-light">İptal</button>
                    </form>
                  </div>
                </div>
              </div>

}

WebApplication11/Views/Writer/WriterFooterPartial.cshtml
<footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © Tüm hakları saklıdır | @DateTime.Now.Year</span>
              <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Yazar Paneli <a href="github.com/dilaranuraltiparmak" target="_blank">ASP.NET Core Projesi</a></span>
            </div>
          </footer>

WebApplication11/Views/Writer/WriterMail.cshtml
@{
    Layout = null;
}
<h1>Yazar mail paneli</h1>

WebApplication11/Views/Writer/WriterNavbarPartial.cshtml
 <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-profile">
              <a href="#" class="nav-link">
                <div class="nav-profile-image">
                  <img src="~/web/images/dna.png" alt="profile">
                  <span class="login-status online"></span>
                  <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                  <span class="font-weight-bold mb-2">Dilara Nur Altıparmak</span>
                  <span class="text-secondary text-small">Yazılım mühendisi</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">PROFİL</span>
                <i class="mdi mdi-contacts menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Writer/WriterMessage/">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
              </a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Bildirimler
                </span>
                <i class="mdi mdi-notification-clear-all menu-icon"></i>
              </a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
              </a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Writer/LogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout-variant menu-icon"></i>
              </a>
            </li>
          </ul>
        </nav>

WebApplication11/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}

<h1>burası yazar profil sayfası</h1>